### ISSUE TITLE
Compile Error: std not in class path

### ISSUE THREAD

**Issue by onehundredfeet** [RobertBorghese/Haxe-to-UnboundCPP#5]
Haxe-to-UnboundCPP/src/unboundcompiler/UnboundCompiler.hx:437: characters 15-28 : Type not found : ucpp.Compiler

since I'm including using haxelib, the class path only seems to find src and not std.

**Comment by onehundredfeet** [comment]
Adding : --class-path ../../Haxe-to-UnboundCPP/std to my project worked, not sure how to fix this given multiple paths in the haxelib.

**Comment by RobertBorghese** [comment]
Hello! This could possibly be due to incorrect installation? Check out the instructions at [here](https://github.com/RobertBorghese/Haxe-to-UnboundCPP#nightly-installation).

The `nightly` part at the end of the `haxelib git` command is important, since that's the branch that combines all the source folders together for distribution. 😅

**Comment by onehundredfeet** [comment]
Yup.   I was working out of the repo.

Thanks.
